steps:
    - name: gcr.io/cloud-builders/docker
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/sys-sync-api:${SHORT_SHA}', '.']
    
    - name: 'gcr.io/cloud-builders/docker'
      args: ["push", "gcr.io/$PROJECT_ID/sys-sync-api"]
    
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['beta', 'run', 'deploy', 'sys-sync-api', '--image', 'gcr.io/$PROJECT_ID/sys-sync-api:${SHORT_SHA}', '--region', 'us-east1', '--platform', 'managed']
images:
    - 'gcr.io/$PROJECT_ID/sys-sync-api'